<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Content Include="settings.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <ProjectReference Include="..\Capstone.Core\Capstone.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
